/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TikkunTzaneretLeloHeresRouteImport } from './routes/tikkun-tzaneret-lelo-heres'
import { Route as SewerCameraInspectionRouteImport } from './routes/sewer-camera-inspection'
import { Route as PatchPipeRepairRouteImport } from './routes/patch-pipe-repair'
import { Route as CippPipeReliningRouteImport } from './routes/cipp-pipe-relining'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'

const TikkunTzaneretLeloHeresRoute = TikkunTzaneretLeloHeresRouteImport.update({
  id: '/tikkun-tzaneret-lelo-heres',
  path: '/tikkun-tzaneret-lelo-heres',
  getParentRoute: () => rootRouteImport,
} as any)
const SewerCameraInspectionRoute = SewerCameraInspectionRouteImport.update({
  id: '/sewer-camera-inspection',
  path: '/sewer-camera-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchPipeRepairRoute = PatchPipeRepairRouteImport.update({
  id: '/patch-pipe-repair',
  path: '/patch-pipe-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const CippPipeReliningRoute = CippPipeReliningRouteImport.update({
  id: '/cipp-pipe-relining',
  path: '/cipp-pipe-relining',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cipp-pipe-relining': typeof CippPipeReliningRoute
  '/patch-pipe-repair': typeof PatchPipeRepairRoute
  '/sewer-camera-inspection': typeof SewerCameraInspectionRoute
  '/tikkun-tzaneret-lelo-heres': typeof TikkunTzaneretLeloHeresRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cipp-pipe-relining': typeof CippPipeReliningRoute
  '/patch-pipe-repair': typeof PatchPipeRepairRoute
  '/sewer-camera-inspection': typeof SewerCameraInspectionRoute
  '/tikkun-tzaneret-lelo-heres': typeof TikkunTzaneretLeloHeresRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge': typeof KnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cipp-pipe-relining': typeof CippPipeReliningRoute
  '/patch-pipe-repair': typeof PatchPipeRepairRoute
  '/sewer-camera-inspection': typeof SewerCameraInspectionRoute
  '/tikkun-tzaneret-lelo-heres': typeof TikkunTzaneretLeloHeresRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cipp-pipe-relining'
    | '/patch-pipe-repair'
    | '/sewer-camera-inspection'
    | '/tikkun-tzaneret-lelo-heres'
    | '/knowledge/$slug'
    | '/knowledge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cipp-pipe-relining'
    | '/patch-pipe-repair'
    | '/sewer-camera-inspection'
    | '/tikkun-tzaneret-lelo-heres'
    | '/knowledge/$slug'
    | '/knowledge'
  id:
    | '__root__'
    | '/'
    | '/cipp-pipe-relining'
    | '/patch-pipe-repair'
    | '/sewer-camera-inspection'
    | '/tikkun-tzaneret-lelo-heres'
    | '/knowledge/$slug'
    | '/knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CippPipeReliningRoute: typeof CippPipeReliningRoute
  PatchPipeRepairRoute: typeof PatchPipeRepairRoute
  SewerCameraInspectionRoute: typeof SewerCameraInspectionRoute
  TikkunTzaneretLeloHeresRoute: typeof TikkunTzaneretLeloHeresRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tikkun-tzaneret-lelo-heres': {
      id: '/tikkun-tzaneret-lelo-heres'
      path: '/tikkun-tzaneret-lelo-heres'
      fullPath: '/tikkun-tzaneret-lelo-heres'
      preLoaderRoute: typeof TikkunTzaneretLeloHeresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sewer-camera-inspection': {
      id: '/sewer-camera-inspection'
      path: '/sewer-camera-inspection'
      fullPath: '/sewer-camera-inspection'
      preLoaderRoute: typeof SewerCameraInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch-pipe-repair': {
      id: '/patch-pipe-repair'
      path: '/patch-pipe-repair'
      fullPath: '/patch-pipe-repair'
      preLoaderRoute: typeof PatchPipeRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cipp-pipe-relining': {
      id: '/cipp-pipe-relining'
      path: '/cipp-pipe-relining'
      fullPath: '/cipp-pipe-relining'
      preLoaderRoute: typeof CippPipeReliningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CippPipeReliningRoute: CippPipeReliningRoute,
  PatchPipeRepairRoute: PatchPipeRepairRoute,
  SewerCameraInspectionRoute: SewerCameraInspectionRoute,
  TikkunTzaneretLeloHeresRoute: TikkunTzaneretLeloHeresRoute,
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
